# -*- coding: utf-8 -*-
"""Architecture.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1C31LvS0S05mh9SM9KtqPSlrpF6XMQCoP
"""

import tensorflow as tf
from tensorflow.keras.layers import Conv2D, MaxPooling2D, Flatten, Dense, Dropout, Input
from tensorflow.keras.models import Sequential

def alexnet():
    model = Sequential([
        Input(shape=(227, 227, 3)),  # Explicit Input layer
        Conv2D(96, (11, 11), strides=4, activation='relu'),
        MaxPooling2D(pool_size=(3, 3), strides=2),
        Conv2D(256, (5, 5), activation='relu', padding='same'),
        MaxPooling2D(pool_size=(3, 3), strides=2),
        Conv2D(384, (3, 3), activation='relu', padding='same'),
        Conv2D(384, (3, 3), activation='relu', padding='same'),
        Conv2D(256, (3, 3), activation='relu', padding='same'),
        MaxPooling2D(pool_size=(3, 3), strides=2),
        Flatten(),
        Dense(4096, activation='relu'),
        Dropout(0.5),
        Dense(4096, activation='relu'),
        Dropout(0.5),
        Dense(10, activation='softmax')
    ])
    return model

# Print AlexNet model summary
alexnet_model = alexnet()
alexnet_model.summary()